# Generated by Django 4.0.6 on 2022-10-07 11:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('photo', models.ImageField(blank=True, upload_to='user_img')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('img_banner', models.ImageField(blank=True, upload_to='user_img')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Create_Ad',
            fields=[
                ('repeatfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CrossApp.repeatfield')),
                ('titre', models.CharField(default='ND', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='ad')),
                ('price', models.FloatField(max_length=100)),
                ('living_area', models.CharField(default='....', max_length=100)),
                ('total_area', models.CharField(default='....', max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('year_built', models.CharField(max_length=10)),
                ('for_rent', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=40)),
                ('more_info', models.TextField(max_length=400)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_ad', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('CrossApp.repeatfield',),
        ),
    ]
