# Generated by Django 4.0.6 on 2022-10-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='img_banner',
        ),
        migrations.AddField(
            model_name='create_ad',
            name='nbres_pieces',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='create_ad',
            name='price_for_rent',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='create_ad',
            name='price_on_sale',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.CharField(default='..', max_length=70),
        ),
        migrations.AlterField(
            model_name='create_ad',
            name='more_info',
            field=models.TextField(max_length=3000),
        ),
    ]
