# Generated by Django 4.0.6 on 2022-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0002_remove_create_ad_price_remove_myuser_img_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ad',
            name='price_for_rent',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_ad',
            name='price_on_sale',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='job',
            field=models.CharField(max_length=40),
        ),
    ]
