# Generated by Django 4.0.6 on 2022-10-08 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0003_alter_create_ad_price_for_rent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('repeatfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CrossApp.repeatfield')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('comment', models.TextField(max_length=250)),
                ('author_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_comment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('CrossApp.repeatfield',),
        ),
    ]
