# Generated by Django 4.0.6 on 2022-10-08 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0005_create_ad_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ad',
            name='comment_author',
        ),
        migrations.AddField(
            model_name='create_ad',
            name='comments_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to='CrossApp.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
