# Generated by Django 4.0.6 on 2022-10-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0007_remove_create_ad_comments_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_user',
        ),
        migrations.AddField(
            model_name='comments',
            name='ad_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_comments', to='CrossApp.create_ad'),
        ),
    ]
