# Generated by Django 4.0.6 on 2022-10-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0008_remove_comments_comments_user_comments_ad_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
