# Generated by Django 4.0.6 on 2022-10-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0009_remove_comments_email_remove_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=350),
        ),
    ]
