# Generated by Django 4.0.6 on 2022-10-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0011_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='number_comments',
            field=models.FloatField(default=0),
        ),
    ]
