# Generated by Django 4.0.6 on 2022-10-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrossApp', '0013_remove_comments_number_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ad',
            name='number_comments',
        ),
    ]
